INSERT INTO tbl_kra_keyvalue_pair(master_id,master_name,kra_key,kra_value) values
('1','STATE','01','Andaman & Nicobar Islands'),
('1','STATE','02','Andhra Pradesh'),
('1','STATE','03','Arunachal Pradesh'),
('1','STATE','04','Assam'),
('1','STATE','05','Bihar'),
('1','STATE','06','Chandigarh'),
('1','STATE','07','Dadra & Nagar Haveli'),
('1','STATE','08','Daman & Diu'),
('1','STATE','09','Delhi'),
('1','STATE','10','Goa'),
('1','STATE','11','Gujarat'),
('1','STATE','12','Haryana'),
('1','STATE','13','Himachal Pradesh'),
('1','STATE','14','Jammu & Kashmir'),
('1','STATE','15','Karnataka'),
('1','STATE','16','Kerala'),
('1','STATE','17','Lakhswadeep'),
('1','STATE','18','Madhya Pradesh'),
('1','STATE','19','Maharashtra'),
('1','STATE','20','Manipur'),
('1','STATE','21','Meghalaya'),
('1','STATE','22','Mizoram'),
('1','STATE','23','Nagaland'),
('1','STATE','24','Orissa'),
('1','STATE','25','Pondicherry'),
('1','STATE','26','Punjab'),
('1','STATE','27','Rajasthan'),
('1','STATE','28','Sikkim'),
('1','STATE','29','Tamil Nadu'),
('1','STATE','30','Tripura'),
('1','STATE','31','Uttar Pradesh'),
('1','STATE','32','West Bengal'),
('1','STATE','33','Chhattisgarh'),
('1','STATE','34','Uttaranchal'),
('1','STATE','35','Jharkhand'),
('1','STATE','99','Others (please specify)');