package in.codifi.api.utilities;

public class MessageConstants {
	public static final String PARAMETER_NULL = "The Given Parameter is null";
	public static final String MOBILE_NUMBER_NULL = "The given Mobile Number is null";
	public static final String EMAIL_ID_NULL = "The given Email Id is null";
	public static final String PAN_NUMBER_NULL = "The given Pan Number is null";
	public static final String USER_ID_NULL = "The given user Id is null";
	public static final String USER_ID_INVALID = "The given user Id is Invalid";
	public static final String MOBILE_NUMBER_WRONG = "The given Mobile Number is wrong";
	public static final String EMAIL_ID_WRONG = "The given Email Id is wrong";
	public static final String EMAIL_ID_ALREADY_AVAILABLE = "The given Email Id is already available for Different Number";
	public static final String PAN_ALREADY_AVAILABLE = "The given PAN Number is already available";
	public static final String ERROR_WHILE_GENERATE_OTP = "Error Occur While Generating OTP";
	public static final String ERROR_WHILE_VERIFY_OTP = "Error Occur While Verifying OTP";
	public static final String INVALID_OTP = "The Given OTP is Invalid";
	public static final String INVALID_OTP_TRY_AFTER = "The Given OTP is Invalid Try again after ";
	public static final String RETRY_OTP_TRY_AFTER = "Please Request OTP after ";
	public static final String OTP_TIME_EXPIRED = "Your OTP Time Expired";
	public static final String SMS_OTP_NOT_VERIFIED = "Sms OTP Not Verified";
	public static final String WRONG_USER_ID = "User Id is Wrong";
	public static final String MANDATORY_FIELDS_NULL = "Mandatory Fileds are null";
	public static final String EKYC_ACTIVE_CUSTOMER = "An Account already exists with the Mobile Number.Please try with another Mobile Number";
	public static final String EKYC_EMAIL_ACTIVE_CUSTOMER = "An Account already exists with the Email ID.Please try with another Email ID";
	public static final String EKYC_DORMANT_CUSTOMER = "Your account is Dormant / Closed. Click to Proceed for Re-KYC";
	public static final String PAN_FILE_USAGE = "usage: java p2j certi.pfx pfxpswd oupt.jks";
	public static final String PAN_KEY_STORE_MSG = "Unable to access input keystore: ";
	public static final String PAN_FILE_NOT_WRITE = "Output file is not writable: ";
	public static final String PAN_KEYSTORE_SUC_MSG = "Java Key Store created successfully";
	public static final String PAN_PKCS7GEN = "java pkcs7gen output.jks pfxpswd dataToBeSigned oupt.sig";
	public static final String PAN_SIGN_OUT = "Signature file written to ";
	public static final String PAN_EXE_MSG = " ::Exception: ";
	public static final String PAN_PRG_SRT_TIME = " ::Program Start Time:";
	public static final String PAN_PRG_NO = " ::nonce= ";
	public static final String INVALID_PAN_MSG = "Invalid Pan Card. Please contact system administrator";
	public static final String ERROR_WHILE_SAVING_DOB = "Error Occur While Saving DOB";
	public static final String DIGI_CODE_NULL = "Digi Code is null";
	public static final String DIGI_STATE_NULL = "Digi State is null";
	public static final String FAILED_HTTP_CODE = "Failed : HTTP error code :";
	public static final String DIGI_SYSOUT_BR = "the br1:";
	public static final String ERR_NO_ACC_TOKEN = "No Access Token Generated From Digilocker";
	public static final String ERR_ACC_TOKEN = "Error while generate access Token";
	public static final String ERR_SAVE_DIGI = "Error while Saving address. Please contact system administrator";
	public static final String ERROR_WHILE_SAVING_PROFILE = "Error Occur While Saving Profile";
	public static final String ERROR_WHILE_SAVING_BANK_DETAILS = "Error Occur While Saving Bank Details";
	public static final String USER_NOT_VERIFIED = "You are not verified Customer please reverified";
	public static final String IFSC_INVALID = "The given user IFSC Code is Invalid";
	public static final String NOMINEE_AVAILABLE = "Nominee Details already Available";
	public static final String ERROR_WHILE_SAVING_NOMINEE_DETAILS = "Error Occur While Saving Nominee Details";
	public static final String ERROR_WHILE_SAVING_SEGMENT_DETAILS = "Error Occur While Saving Segment Details";
}
